### ISSUE TITLE
Cannot change password within the app on Android

### ISSUE THREAD

**Issue by AndrewBHolder** [mymonero/mymonero-android-js#30]
The Issue is pretty simple, on the desktop app in the Preferences section, there is an option to change the password, but that option is not available on the Android app in the Preferences section.

**Comment by karlbuys** [comment]
Hi Andrew

Thank you for reporting this.

At present, this is due to a known issue with the wallet. Due to the possibility of data corruption, we have disabled the "Change Pin" button for the time being, with a view to ensuring that people's wallets aren't affected negatively. We plan to address this bug and reintroduce the button after making 100% certain that the potential for data corruption has been fully addressed.

Please refer to #13
